//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShapeClipController.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShapeClipController.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.
        /// </summary>
        internal static string OP_EXEC {
            get {
                return ResourceManager.GetString("OP_EXEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~.
        /// </summary>
        internal static string OP_PAUSE {
            get {
                return ResourceManager.GetString("OP_PAUSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @.
        /// </summary>
        internal static string OP_UPLOAD {
            get {
                return ResourceManager.GetString("OP_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShapeClip Controller.
        /// </summary>
        internal static string TITLEBAR_MAIN {
            get {
                return ResourceManager.GetString("TITLEBAR_MAIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Connected Clip.
        /// </summary>
        internal static string TITLEBAR_NOPORT {
            get {
                return ResourceManager.GetString("TITLEBAR_NOPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ▶.
        /// </summary>
        internal static string TOGGLEBTN_START {
            get {
                return ResourceManager.GetString("TOGGLEBTN_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ■.
        /// </summary>
        internal static string TOGGLEBTN_STOP {
            get {
                return ResourceManager.GetString("TOGGLEBTN_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        internal static string UPLOADBTN_UPLOAD {
            get {
                return ResourceManager.GetString("UPLOADBTN_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOADING.
        /// </summary>
        internal static string UPLOADBTN_UPLOADING {
            get {
                return ResourceManager.GetString("UPLOADBTN_UPLOADING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VERIFYING.
        /// </summary>
        internal static string UPLOADBTN_VERIFYING {
            get {
                return ResourceManager.GetString("UPLOADBTN_VERIFYING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAITING.
        /// </summary>
        internal static string UPLOADBTN_WAITING {
            get {
                return ResourceManager.GetString("UPLOADBTN_WAITING", resourceCulture);
            }
        }
    }
}
